name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup msbuild
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup nuget
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Nuget restore
      run: nuget restore HSPI_LiftMasterMyQ.sln
      
    - name: MSBuild
      run: |
        msbuild /p:Configuration=Debug HSPI_LiftMasterMyQ.sln
        msbuild /p:Configuration=Release HSPI_LiftMasterMyQ.sln
        
    - name: Stage artifacts
      run: |
        mkdir artifacts
        cp bin\Release\HSPI_LiftMasterMyQ.exe artifacts\HSPI_LiftMasterMyQ.exe
        mkdir "artifacts\Debug Build"
        cp bin\Debug\HSPI_LiftMasterMyQ.exe "artifacts\Debug Build\HSPI_LiftMasterMyQ.exe"
        echo %GITHUB_SHA% > artifacts\CommitHash.txt
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Plugin
        path: artifacts


